### ISSUE TITLE
Why new pixhawk hardware use USB3.0?

### ISSUE THREAD

**Issue by South-River** [pixhawk/Hardware#108]
Hi!
I used pixhawk for two years. I noticed that new versions of pixhawk use USB3.0 for communication. But as far as I know, there's no large data sent and received by pixhawk. Although IMU needs high frequency, maybe IIC and SPI can do this job.
So I'm wondering why new pixhawk use USB3.0?
Thanks!

**Comment by davids5** [comment]
On the new V5X, V6X , It is a type C connector with USB 2.0 FS signaling. HS is not used.
