### ISSUE TITLE
How to connect pixhawk 2.4.8 to Nvidia Jetson Nano?

### ISSUE THREAD

**Issue by atmadeep** [pixhawk/Hardware#95]
Hi, I'm working on making a semi autonomous drone using vision based methods. Has anyone tried connecting a pixhawk 2.4.8 with jetson Nano? Any help would be appreciated

**Comment by dogmaphobic** [comment]
<img width="906" alt="Screen Shot 2019-08-20 at 8 59 47 AM" src="https://user-images.githubusercontent.com/749243/63349249-0404a700-c329-11e9-982c-9cb290f7b099.png">

The UART pins are separate for easy reach.

**Comment by atmadeep** [comment]
Have you tested this over ROS? Can you get the messages in mavros?

**Comment by dogmaphobic** [comment]
Yes, there isn't really any difference than running mavros on an RPI or an Intel NUC (running a Debian Linux).

**Comment by atmadeep** [comment]
Thank you very much.

**Comment by atmadeep** [comment]
New problem here, Every time I connect jetson nano to pixhawk, it turns off and won't start again until disconnected. I'm not connecting the red/power cable. 
What can be the problem now?

**Comment by pkocmoud** [comment]
@atmadeep This is really not a place for usage assistance. You would have better luck in one of the discuss forums.

Depending on the flight software you are using you might try: 

PX4: https://discuss.px4.io/
Ardupilot: https://discuss.ardupilot.org/

**Comment by proficnc** [comment]
Make sure your voltage levels are correct on your io

**Comment by busradurak** [comment]
> New problem here, Every time I connect jetson nano to pixhawk, it turns off and won't start again until disconnected. I'm not connecting the red/power cable.
> What can be the problem now?
Try to give power only the nano if you connect to power both of them, some problem might be occured.

**Comment by oguzhanonder38** [comment]
> > New problem here, Every time I connect jetson nano to pixhawk, it turns off and won't start again until disconnected. I'm not connecting the red/power cable.
> > What can be the problem now?
> > Try to give power only the nano if you connect to power both of them, some problem might be occured.

Hello busra have you solved connection problem? If you solved the problem, please connect to me. Thx. : *

**Comment by reinzler** [comment]
Hi, guys,  I usually have same problem, if Pixhawk had been connected to Jetson Nano before I powered on the Nano, Nano cant detect Pixhawk until I physically disconnect/ connect MicroUSB cable, Did someone find an answer?

**Comment by hamishwillee** [comment]
Not the best place for this question - https://github.com/pixhawk/Hardware/issues/95#issuecomment-560539815

But if you find an answer cross post.
